### PR TITLE
Add option to change the JVM target when testing code generators with the custom `AnvilCompilation` class

### LINKED ISSUE #682: Allow configuration of KotlinCompiler used in AnvilCompilation to set jvm target
Hi there,
I just upgraded a project to target java 11 and I have a unit test for a custom annotation which uses the internal `compileAnvil` method.

https://github.com/square/anvil/blob/4b925f7b50e330acafa396e239a03bcf7858671a/compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt#L193
The JVM target is hard-coded to target 1.8 and when I run the test it fails with the following error:

`Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`

Would it be possible to allow the user to configure the JVM target for the `compileAnvil` method?

### PR DESCRIPTION
**Pull request by vRallev**
Fixes #682

### CODE REVIEW

**Comment by RBusarow** [comment]
The system property `java.vm.specification.version` holds the version strings like "1.8", "11", etc.

So, it's possible to set the target's default based upon the runtime, instead of the hard-coded 1.8.

```kotlin
companion object {
  public operator fun invoke(): AnvilCompilation {
    return AnvilCompilation(
      KotlinCompilation().apply {
        // ...
        jvmTarget = JvmTarget.fromString(System.getProperty("java.vm.specification.version"))
        // ...
      }
    )
  }
}
```

**Comment by vRallev** [comment]
> The system property `java.vm.specification.version` holds the version strings like "1.8", "11", etc.
> 
> So, it's possible to set the target's default based upon the runtime, instead of the hard-coded 1.8.
> 
> ```kotlin
> companion object {
>   public operator fun invoke(): AnvilCompilation {
>     return AnvilCompilation(
>       KotlinCompilation().apply {
>         // ...
>         jvmTarget = JvmTarget.fromString(System.getProperty("java.vm.specification.version"))
>         // ...
>       }
>     )
>   }
> }
> ```

I implemented this locally, and then discarded all changes. There's also `Runtime.version().feature()` now. 

The reason why I discarded it is that many projects use newer JDK versions at build time and target older versions at runtime. Most Android projects do that. Anvil itself is doing that. It also opens up the door for different behavior locally and during CI. I changed my mind and believe being explicit is the way to go.

**Comment by RBusarow** [comment]
> It also opens up the door for different behavior locally and during CI.

I was kind of on the fence, but I hadn't considered this one.  I'm convinced. :)

**Review by RBusarow — APPROVED** [review]

**Comment by vRallev** [comment]
We think alike, I had the same idea 😅

**Pull request merged**
