### PR TITLE
Remove the implementation for the old compiler backend.

### LINKED ISSUE #422: Remove support for the old compiler backend
Kotlin 1.6 will deprecate the old compiler backend. The IR compiler backend for JVM/Android projects became the default with Kotlin 1.5. At this point there should be no reason why someone on those platforms still uses the old backend.

Anvil still supports both. But supporting the old backend will become a blocker for #236. Repeated annotations with a runtime / compile time retention are only implemented in the IR backend and not in the old backend. Anvil will remove support for the old backend to support repeated annotations.

My plan is to bump Kotlin 1.6 for Anvil and release a final version supporting both backends. This will unblock anyone still using the old backend and Kotlin 1.6. There is a binary incompatible change within the Kotlin compiler that makes Anvil versions compiled with 1.5 incompatible with 1.6. This last release built with 1.6 for both backends is therefore necessary.

After that support for the old backend will be removed. Newer Anvil versions will only support the IR backend.

### PR DESCRIPTION
**Pull request by vRallev**
The stub generating Gradle task uses the IR backend by default starting with Kotlin 1.8.20. We no longer need to support the old backend therefore.

Fixes #422

### CODE REVIEW

**Comment by vRallev** [comment]
7 tests are failing that use the Kotlin compile testing library and rely on Anvil to run during the stub generation. This issue doesn't seem to happen normally and only when using Kotlin compile testing.

Anvil uses an `IrGenerationExtension` to add the Dagger `@Component` annotation whenever `@MergeComponent` is used. This has to happen in the stub generating task, because Dagger must see the `@Component` annotation. In normal Kotlin compilations I can see the `@Component` annotation being added to the stubs, but not with Kotlin compile testing. With Kotlin compile testing I see how `AnvilComponentRegistrar` is called and the IR extension is registered for the stub task, but it’s not called in the stub generating task for some reason.

Because the `@Component` annotation isn't added Dagger doesn't run and the tests fail. These 7 tests are the only tests exercising this codepath and relying on that behavior.

**Comment by vRallev** [comment]
After further testing I noticed that `kapt.use.jvm.ir` makes no difference and the tests fail because the implementation for the old backend `ModuleMerger` has been removed. With the Kotlin compile testing library we always exercise old backend codepath no matter what.

**Comment by vRallev** [comment]
The new compile testing library fixes that.

**Review by JoelWilcox — APPROVED** [review]
🙌

**Comment by vRallev** [comment]
This PR evolved over 9 months and finally can be merged 🙌

**Pull request merged**
